version: '3'

services:

  go-rest-example-db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env

  go-rest-example:
    build: .
    ports:
      - "8040:8040"
    depends_on:
      - go-rest-example-db
    environment:
      # These are defined in config.go
      - GO_REST_EXAMPLE_DATABASE_HOSTNAME=go-rest-example-db
      - GO_REST_EXAMPLE_DATABASE_USERNAME=root
      - GO_REST_EXAMPLE_DATABASE_PASSWORD=password
      - GO_REST_EXAMPLE_DATABASE_SCHEMA=go-rest-example-db
    env_file:
      - .env

volumes:
  db_data:
